### ISSUE TITLE
Need Windows pre-compiled binaries

### ISSUE THREAD

**Issue by SumatraPeter** [drake7707/epubspellchecker#1]
I don't see anything listed under **[Releases](https://github.com/drake7707/epubspellchecker/releases)** yet. Am I missing something?

Please add pre-compiled binaries for the latest version to the Releases section for those of us who don't want to fiddle with the code. Thanks!

**Comment by drake7707** [comment]
Ah yes good point thanks, the old codeplex https://epubspellchecker.codeplex.com/ had a published release. I've copied it over now, https://github.com/drake7707/epubspellchecker/releases/tag/v1003
